#include "/Engine/Private/Common.ush"
#include "MC_Tables.ush"

uint NumCells;

StructuredBuffer<uint> CaseIndexPerCell;
StructuredBuffer<uint> TriOffsets;
RWStructuredBuffer<uint> OutIndices;

[numthreads(256,1,1)]
void Main(uint3 DTid : SV_DispatchThreadID)
{
    uint cell = DTid.x;
    if (cell >= NumCells) return;

    uint caseIndex = CaseIndexPerCell[cell];
    if (caseIndex == 0 || caseIndex == 255) return;

    uint baseIndex = TriOffsets[cell] * 3;

    [unroll]
    for (uint t = 0; t < 16; t += 3)
    {
        int e0 = TriTable[caseIndex][t + 0];
        if (e0 < 0) break;

        // Indexless: just sequential
        OutIndices[baseIndex + 0] = baseIndex + 0;
        OutIndices[baseIndex + 1] = baseIndex + 1;
        OutIndices[baseIndex + 2] = baseIndex + 2;

        baseIndex += 3;
    }
}
